<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "<%= typo3ProviderExtension.extkey %>"
 *
 * Auto generated by the Tollwerk Yeoman Generator (https://github.com/tollwerk/generator-tollwerk)
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Project: <%= title %>',
    'description' => 'Custom features for <%= title %>',
    'category' => 'misc',
    'author' => 'tollwerk GmbH',
    'author_email' => 'info@tollwerk.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.0.0-',
            'vhs' => '5.0.0-'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
